function isMobileDevice(){return(typeof window.orientation!=="undefined"||navigator.userAgent.indexOf("IEMobile")!==-1);}
$(document).ready(function(){var csrfToken=$('meta[name="csrf-token"]').attr("content");$.ajaxPrefilter(function(options,originalOptions,jqXHR){if(options.processData&&options.type.toLowerCase()==="post"){options.data=options.data||"";options.data+=options.data?"&":"";if(csrfToken){options.data+="csrf_token="+encodeURIComponent(csrfToken);}}});});$(document).ready(function(){setTimeout(function(){$(".alert").fadeOut();},4000);});$(document).ready(function(){$("body").removeClass("preload");});$(document).ready(function(){var maxLength=255;$(".limitedText").keyup(function(){var textlen=maxLength-$(this).val().length;$("#rchars").text(textlen);});});$(document).ready(function(){$("#setup_url").on("input",function(){$("#regurl").html("/"+$("#setup_url").val().toLowerCase());});});$(document).ready(function(){$(document).on("click",".linkBox",function(){$(".linkBoxInput",$(this)).select();$(".linkBoxCopied",$(this)).fadeIn(200);$(".linkBoxCopied",$(this)).delay(1000).fadeOut(200);document.execCommand("copy");});});$(document).ready(function(){$(document).on("click","#closeWarning",function(){$(".profileContentWarning").fadeOut(200);});});$(document).ready(function(){$("#showFullCreate").click(function(){$("#addProfile").toggle();$("#queMenu").toggle();});$("#hideProfileQue").click(function(){$("#addProfile").toggle();$("#queMenu").toggle();});$("#hidePersonalizeQue").click(function(){$("#quePersonalize").toggle();$("#queMenu").toggle();});$("#showFullPersonalize").click(function(){$("#quePersonalize").toggle();$("#queMenu").toggle();});});$(function(){$("#adminShowItems").click(function(){$("#adminItems").toggle();$("#adminLog").hide();$("#noteBlock").hide();$("#adminVerificationBlock").hide();});$("#adminShowOverview").click(function(){$("#adminItems").hide();$("#adminLog").hide();$("#noteBlock").hide();$("#adminVerificationBlock").toggle();});$("#adminShowLog").click(function(){$("#adminItems").hide();$("#adminLog").toggle();$("#noteBlock").hide();$("#adminVerificationBlock").hide();});$("#adminShowNotes").click(function(){$("#adminItems").hide();$("#adminLog").hide();$("#noteBlock").toggle();$("#adminVerificationBlock").hide();});if(location.search==="?items=true"){$("#adminShowItems").click();}});$(document).ready(function(){$(document).on("click",'a[data-toggle="collapse"]',function(e){e.preventDefault();var $this=$(this);if($this.attr("disabled")){return false;}
var text=$this.attr("data-toggle-text");if(text){$this.attr("data-toggle-text",$this.text()).text(text);}
var id=$this.attr("href");if($(id).hasClass("active")){$this.removeClass("active");$(".collapse").slideUp(400,function(){$(id).removeClass("active");$(this).removeAttr("disabled");});}else{$this.addClass("active");$(".collapse").slideUp(400,function(){$(this).removeClass("active");$(this).removeAttr("disabled");});$(id).slideDown(400,function(){$(this).addClass("active");$(this).removeAttr("disabled");});}});$(document).on("click",'a[data-toggle="tabs"]',function(e){e.preventDefault();var id=$(this).attr("href");if($(id).hasClass("active")){return false;}
$(".tab").removeClass("active");$('a[data-toggle="tabs"]').removeClass("active");$(this).addClass("active");$(id).addClass("active");});window.activateShiftSlides=function(){$(".slide[data-attach]").each(function(){var form=$(this).closest("form");$(this).appendTo(form).removeAttr("data-attach");});};window.activateSlide=function(id){activateShiftSlides();var $parent=$(id).closest(".slides");var $active=$(".slide.active",$parent).first();if($(id).prevAll().filter($active).length){$active.addClass("wasActive");}
if($active){$active.removeClass("active");if(!$(id).hasClass("wasActive")){$(".modalHeaderBack",id).attr("href","#"+$active.attr("id")).show();}}else{$(".modalHeaderBack").hide();}
$(id).addClass("active").removeClass("wasActive");var inputFocus=$(id+
' > .modalBody input[type="text"],'+
id+
' > .modalBody input[type="number"],'+
id+
" > .modalBody textarea").first();if(inputFocus){setTimeout(function(){inputFocus.focus();},500);}};$(function(){activateShiftSlides();});$(document).on("click",'a[data-toggle="slide"]',function(e){e.preventDefault();var $this=$(this);var id=$this.attr("href")||$this.attr("data-target");var $id=$(id);if($id.hasClass("active")){return false;}
var content=$this.attr("data-content")||$id.attr("data-content");if(content){$parent=$this.closest(".slide");var slideLoading=$this.attr("data-slide-loading");if(slideLoading){$this.buttonLoading();}
$parent.addClass("isLoading");$.get(content,function(html){$id.html(html);activateSlide(id);}).fail(function(){var redirectFail=$id.closest(".slides").attr("data-redirect-on-fail");if(redirectFail){window.location.href=redirectFail;}}).always(function(){$parent.removeClass("isLoading");if(slideLoading){$this.buttonReset();}});}else{activateSlide(id);}});$(document).on("change","#eventType",function(e){var checked=$(this).is(":checked");$('a[href="#eventLocationSlide"]').attr("disabled",checked);});});$(document).on("click",'[data-toggle="follow"]',function(){var $this=$(this);var id=$this.attr("data-account");var following=$this.attr("data-following")==="true";var action=following?"unfollow":"follow";var recommend=$this.attr("data-recommend")==="true";$this.attr("disabled",true);$.post("/interaction",{account:id,action,recommend,}).done(function(data){$('[data-toggle="follow"][data-account="'+id+'"]').each(function(){var elem=$(this);var elemButton=$(".buttonPrimary",elem);var updateElem=elemButton.length?elemButton:elem;if(following){elem.attr("data-following","false");updateElem.text("Follow");}else{elem.attr("data-following","true");updateElem.text("Unfollow");}
if(recommend&&data){$("#account"+id).replaceWith(data);}});}).always(function(){$this.attr("disabled",false);});return false;});$(document).on("click",'[data-toggle="block"]',function(){var $this=$(this);var id=$this.attr("data-account");var blocked=$this.attr("data-blocked")==="true";var action=blocked?"unblock":"block";$this.attr("disabled",true);$.post("/interaction",{account:id,action,}).done(function(){if(blocked){$this.attr("data-blocked","false");$("#blockStatus").html("Block");}else{$this.attr("data-blocked","true");$("#blockStatus").html("Unblock");}}).always(function(){$this.attr("disabled",false);});});$(document).on("click","tr[data-href]",function(event){event.preventDefault();window.location.href=$(this).attr("data-href");return false;});$(function(){$(document).on("click","[data-track-click]",function(){plausible("Click",{props:$(this).data("trackClick")});});$("[data-track-click-immediate]").each(function(){$(this).click();});$("[data-track-view]").each(function(){plausible("View",{props:$(this).data("trackView")});});});$(document).ready(function(){$(".admin-tag").click(function(){id=$(this).attr("data-sub");$("#sub_"+id).toggle();});});$(document).ready(function(){var advanced=document.getElementById("advanced-toggle");if(advanced){advanced.addEventListener("click",function(){$("#add-options").toggle();$("#advanced-display-show").toggle();$("#advanced-display-hide").toggle();},false);}});$(document).ready(function(){var currency=$("#currency").val()??"usd";function calculateShare($price){var multi=100;var cut=$price.attr("data-share")||0.75;var fee=30;var price=$price.val()*multi;var total=price*cut;var fees=total-fee;var dollars=fees/100;var end=dollars.toLocaleString("en-US",{style:"currency",currency,});if(total!=0){$(".priceShareAmount",$("#priceShare")).text(end);$("#priceShare").show();}else{$("#priceShare").hide();}}
$(document).on("change",'input[type="radio"][name="currency"]',function(){currency=$(this).val();symbol=$(this).attr("data-symbol");$(".currency").html(symbol);calculateShare($("#mail_price"));});$(document).on("input","#mail_price",function(){calculateShare($("#mail_price"));});$(document).on("blur",".numrestrict",function(){var num=parseFloat($(this).val());var cleanNum=num.toFixed(2);$(this).val(cleanNum);});});$(document).ready(function(){$("textarea").each(function(){this.setAttribute("style","overflow-y:hidden;");}).on("input",function(){this.style.height="auto";this.style.height=this.scrollHeight+"px";});});function blockSpecialChar(e){var k=e.keyCode;return((k>64&&k<91)||(k>96&&k<123)||k==8||(k>=48&&k<=57));}
$(".no-special-chars").keyup(function(){var start=this.selectionStart;var end=this.selectionEnd;var value=$(this).val();var newValue=value.replace(/[^a-z0-9\-\_]/gi,"");var difference=value.length-newValue.length;$(this).val(newValue);this.setSelectionRange(start-difference,end-difference);});$(document).ready(function(){var origin=window.location.origin;$("#setup_url").keyup(function(){var post_url=$(this).val();$.post(origin+"/checkusername",{url:post_url,},function(data){if(data.status==true){$("#url_error").hide();$("#url_success").show();}else{$("#url_success").hide();$("#url_error").show();}},"json");$("#chooseUsernamePreview").html("direct.me/"+$(this).val());});$("#reg_password").keyup(function(){var password=$(this).val();if(password.length<6||!/[a-z]/i.test(password)||!/\d/.test(password)){$("#password_success").hide();$("#password_error").show();}else{$("#password_error").hide();$("#password_success").show();}});});$(document).ready(function(){var origin=window.location.origin;$("#checkEmail").keyup(function(){var checkEmail=$(this).val();if(checkEmail.length>5){$.post(origin+"/checkEmail.php",{checkEmail:checkEmail,},function(data){if(data.status==true){$("#email_error").hide();$("#email_success").show();}else{$("#email_success").hide();$("#email_error").show();}},"json");}});});$(document).ready(function(){var origin=window.location.origin;$("#inviteCode").keyup(function(){var inviteCode=$(this).val();$.post(origin+"/checkinvite",{code:inviteCode,},function(data){if(data.status==true){$("#invite_error").hide();$("#invite_success").show();}else{$("#invite_success").hide();$("#invite_error").show();}},"json");});});$(function(){var targets=$("[rel~=tooltip]"),target=false,tooltip=false,title=false;targets.bind("mouseenter",function(){target=$(this);tip=target.attr("title");tooltip=$('<div id="tooltip"></div>');if(!tip||tip=="")return false;target.removeAttr("title");tooltip.css("opacity",0).html(tip).appendTo("body");var init_tooltip=function(){if($(window).width()<tooltip.outerWidth()*1.5)
tooltip.css("max-width",$(window).width()/2);else tooltip.css("max-width",340);var pos_left=target.offset().left+
target.outerWidth()/2-
tooltip.outerWidth()/2,pos_top=target.offset().top-tooltip.outerHeight()-20;if(pos_left<0){pos_left=target.offset().left+target.outerWidth()/2-20;tooltip.addClass("left");}else tooltip.removeClass("left");if(pos_left+tooltip.outerWidth()>$(window).width()){pos_left=target.offset().left-
tooltip.outerWidth()+
target.outerWidth()/2+
20;tooltip.addClass("right");}else tooltip.removeClass("right");if(pos_top<0){var pos_top=target.offset().top+target.outerHeight();tooltip.addClass("top");}else tooltip.removeClass("top");tooltip.css({left:pos_left,top:pos_top,}).animate({top:"+=10",opacity:1,},50);};init_tooltip();$(window).resize(init_tooltip);var remove_tooltip=function(){tooltip.animate({top:"-=10",opacity:0,},50,function(){$(this).remove();});target.attr("title",tip);};target.bind("mouseleave",remove_tooltip);tooltip.bind("click",remove_tooltip);});});$(function(){$(document).on("click",".infinite-load-more",function(e){e.preventDefault();e.target.blur();var $this=$(this);$this.addClass("bdisabled");var href=$this.attr("href");$.get(href+"&infinite=1",function(data){var nextPage=$(data).filter('input[name="nextPage"]');if(nextPage[0].value){$this.attr("href",nextPage[0].value);$this.removeClass("bdisabled");}else{$this.remove();}
$(".exploreGrid").append(data);}).always(function(){$this.removeClass("bdisabled");$this.find(".bicon").css("display","inline-block");$this.find(".bspinner").css("display","none");});return false;});});$(function(){window.closeModal=function($modal,ignoreConfirm=false){$modal=$modal||$(".modal.isVisible");if(!$modal.hasClass("isUnclosable")){var data=$modal.data()||{};if(!ignoreConfirm&&$modal.hasClass("dirty")){var result=window.confirm("Are you sure you want to close this form? You'll lose any unsaved changes");if(!result){return;}
$modal.removeClass("dirty");}
if(data.onDismissRedir){location.href=data.onDismissRedir;}else if(data.onDismissOpen){openModal(data.onDismissOpen);}else{$modal.removeClass("isVisible");if($("[data-reset-onclose]",$modal).length){$modal.html(" ");}
if($(".modal.isVisible").length===0){$("body").removeClass("modalOpen");}}
if(data.onDismissCallback){var callback=window[data.onDismissCallback];if(typeof callback==="function"){callback($modal);}}}};window.openModal=function(id){var $modal=$(id+".modal");$(".modal").removeClass("isVisible");$modal.addClass("isVisible");$("body").addClass("modalOpen");};window.minimizeModal=function(){$(".modal.isVisible").addClass("isMinimized");$(".modal").removeClass("isVisible");$("body").removeClass("modalOpen");};window.maximizeModal=function(){$(".modal.isMinimized").addClass("isVisible");$(".modal").removeClass("isMinimized");$("body").addClass("modalOpen");};$.fn.modalLoading=function(){return this.addClass("isLoading").html('<div class="modalLoading"><svg class="bspinner animated infinite spin" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="#8e8e8e" d="M1.379 9.503A15.906 15.906 0 017.715 2.31a2 2 0 112.068 3.424 11.923 11.923 0 00-4.75 5.392c-2.686 6.047.048 13.152 6.094 15.84s13.152-.048 15.84-6.094-.048-13.152-6.094-15.84a11.942 11.942 0 00-4.236-1.02 2 2 0 11.21-3.994c1.95.103 3.85.56 5.65 1.36 8.062 3.582 11.707 13.056 8.124 21.118S17.565 34.204 9.503 30.621-2.204 17.565 1.379 9.503z"/></svg></div>');};$(document).on("click",'[data-toggle="modal"]',function(e){e.preventDefault();$(".modal").removeClass("isVisible");var $this=$(this);var id=$this.attr("data-target");var slide=$this.attr("data-slide");var $modal=$(id+".modal");function activateFirstSlide(){if(!slide){return;}
$(".slide",$modal).removeClass("active");$(slide).addClass("active").removeClass("wasActive");}
var content=$this.attr("data-content");var redirectFail=$this.attr("data-redirect-on-fail");var modalClass=$this.attr("data-modal-class");if(content){if(!$modal.length){$modal=$('<div id="'+
id.substring(1)+
'" class="modal '+
(modalClass?modalClass:"")+
'"></div>').appendTo("body");}
$modal.modalLoading();$.get(content,function(html){$modal.html(html).removeClass("isLoading");var $modalOverlayFeature=$(".modalOverlayFeature",$modal);if($modalOverlayFeature.length){$modalOverlayFeature.css("bottom",$(".modalWithFeaturedOverlay",$modal).height()-30+"px");}
activateFirstSlide();}).fail(function(){if(redirectFail){window.location.href=redirectFail;}});}else{activateFirstSlide();}
$modal.addClass("isVisible").removeClass("isMinimized");$("body").addClass("modalOpen");});$(document).on("click",".modalMinimize",function(e){e.preventDefault();minimizeModal();});$(document).on("click",'[data-dismiss="modal"]',function(e){e.preventDefault();closeModal();});$(document).on("click",".modal.isMinimized",function(e){e.preventDefault();maximizeModal();});$(document).on("click",".iconsGridItem",function(e){e.preventDefault();var icon=$(this).attr("data-title");$('input[name="icon"]').val(icon);$(".iconsSearch").slideUp();$(".iconPreviewSelection").html($(this).html());$(".iconPreview").slideDown();});$(document).on("click",".removeIcon",function(e){e.preventDefault();$('input[name="icon"]').val("");$(".iconPreview").slideUp();$(".iconsSearch").slideDown();});$(document).on("click",".removeImage",function(e){var $this=$(this);$('input[name="icon"]').val("");$('input[name="image"]').val("");var $form=$this.closest("form");var action=$form.attr("data-action");if($form.attr("data-id")){$.post(action,$form.serialize()+"&removeImage=1");}
activateSlide("#form");});$(document).on("keyup",".iconsGridSearch",function(){var value=$(this).val().trim().replace(" ","-").toLowerCase();if(value==""){$(".iconsGridItem").show();}else{$(".iconsGridItem").not('[data-title*="'+value+'"]').hide();}});$(document).on("change",".confirmClose input",function(){$(this).closest(".confirmClose").addClass("dirty");});$(document).on("click",".saveProgress",function(){var $this=$(this);var $form=$this.closest("form");var $slide=$this.closest(".slide");if($slide){$item=$('a[href="#'+$slide.attr("id")+'"]');$('<svg class="inputSaved" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><circle cx="12" cy="12" r="9" /><path d="M9 12l2 2l4 -4" /></svg>').appendTo($item).delay(500).fadeOut(500,function(){$(this).remove();});}
if(!$form.attr("data-id")){return;}
var action=$form.attr("data-action");$.post(action,$form.serialize());$this.closest(".confirmClose").removeClass("dirty");});var $openModals=$(".modal.isVisible");if($openModals.length){var $modal=$openModals.first();if(!$modal.hasClass("noOverlay")){$("body").addClass("modalOpen");}
var content=$modal.attr("data-content");if(content){$.get(content,function(html){$modal.html(html);});}
var $modalOverlayFeature=$(".modalOverlayFeature");if($modalOverlayFeature.length){$modalOverlayFeature.css("bottom",$(".modalWithFeaturedOverlay",$openModals).height()-30+"px");}}});$(function(){$(document).on("click",".formStepNext",function(e){e.preventDefault();var parent=$(this).parents("form");$(".formStep1",parent).slideUp();$(".formStep2",parent).slideDown();$(".formStep2 input",parent).focus();return false;});});$(function(){var dropped;window.sortable=function(){if($.isFunction($.fn.sortable)){$(".sortable").sortable({cursor:"move",handle:".editProfileElementPosition",opacity:0.5,items:"div.editProfileElement:not(.active)",refreshPositions:true,placeholder:"editProfileElementPlaceholder",start:function(event,ui){dropped=false;},update:function(event,ui){if(dropped){return;}
$("#profileItems").addClass("loading");var items=$(this).sortable("serialize");var itemId=$(ui.item).attr("data-item-id");var parentId=0;var parent=$(ui.item).closest(".editProfileElementFolder");if(parent.length){parentId=parent.attr("data-item-id");}else{$(".editProfileElementFolder").removeClass("active");$(".editProfileElementNested").slideUp();}
$.post("/me/items/reorder",items+"&itemId="+itemId+"&parentId="+parentId).done(function(data){$("#profileItems").html(data).removeClass("loading");sortable();});},}).disableSelection();}
if($.isFunction($.fn.droppable)){$(".droppable").droppable({accept:"div.editProfileElement:not(.editProfileElementFolder):not(.editProfileElementGifts)",tolerance:"pointer",drop:function(event,ui){dropped=true;$("#profileItems").addClass("loading");var itemId=$(ui.draggable).attr("data-item-id");$(ui.draggable).remove();var parentId=$(this).attr("data-item-id");$.post("/me/items/reorder",{itemId,parentId,}).done(function(data){$("#profileItems").html(data).removeClass("loading");sortable();});},});$(".editProfileElementFolder.active").droppable("option","disabled",true);}};sortable();$(document).on("click",".showFolder",function(e){e.preventDefault();var $this=$(this);if($this.attr("disabled")){return false;}
var $folder=$this.closest(".editProfileElementFolder");var id=$this.attr("href");$this.attr("disabled",true);if($(id).hasClass("active")){$(id).slideUp(400,function(){$(id).removeClass("active");$this.removeAttr("disabled");});$this.html("(Show folder)");}else{$(".collapse").slideUp(400,function(){$(this).removeClass("active");});$(id).slideDown(400,function(){$(this).addClass("active");$this.removeAttr("disabled");});$this.html("(Close folder)");}
if($folder.hasClass("active")){$(".editProfileElementFolder").removeClass("active");$folder.droppable("option","disabled",false);}else{$folder.addClass("active");$folder.droppable("option","disabled",true);}});$(document).on("change","input[type=checkbox][data-action]",function(e){var $this=$(this);var action=$this.attr("data-action");var callback=$this.attr("data-callback");var checked=$this.is(":checked");$.post(action,{checked,}).done(function(data){if(callback){callback=window[callback];if(typeof callback==="function"){callback(data,$this);}}else if(data){displaySuccess(data);}}).fail(function(error){displayError(error.responseText);$this.toggle(checked);});});window.unhideItemCallback=function(data,$this){var $parent=$this.closest(".editProfileElement");if($this.is(":checked")){$parent.removeClass("hidden");}else{$parent.addClass("hidden");}
if(data){displaySuccess(data);}};window.showItemShareCallback=function(data,$this){var id=$this.attr("data-id");activateSlide("#shareMainMenu"+id);if(data){displaySuccess(data);}};window.itemAddCallback=function(data){try{var data=$.parseJSON(data);if(data.message){displaySuccess(data.message);}
closeModal(null,true);}catch(e){displayError("Your item couldn't be saved");}};window.closeAddItemModalCallback=function(){$.get("/me",function(html){$("#profileItems").html(html);sortable();});};$.fn.buttonLoading=function(){return this.attr("disabled",true).prepend('<svg style="display: inline-block "class="buttonSpinner animated infinite spin" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="currentColor" d="M1.379 9.503A15.906 15.906 0 017.715 2.31a2 2 0 112.068 3.424 11.923 11.923 0 00-4.75 5.392c-2.686 6.047.048 13.152 6.094 15.84s13.152-.048 15.84-6.094-.048-13.152-6.094-15.84a11.942 11.942 0 00-4.236-1.02 2 2 0 11.21-3.994c1.95.103 3.85.56 5.65 1.36 8.062 3.582 11.707 13.056 8.124 21.118S17.565 34.204 9.503 30.621-2.204 17.565 1.379 9.503z"/></svg>');};$.fn.buttonReset=function(){$(".buttonSpinner",this).remove();return this.attr("disabled",false);};$(document).on("submit","form[action]",function(){$('.button[type="submit"]',$(this)).buttonLoading();});$(document).on("submit","form[data-action]",function(e){e.preventDefault();var $this=$(this);var action=$this.attr("data-action");var callback=$this.attr("data-callback");var slide=$this.attr("data-slide");$('button[type="submit"]',$this).buttonLoading();$.post(action,$this.serialize()).done(function(data){if(callback){callback=window[callback];if(typeof callback==="function"){callback(data,$this);}}else if(data){try{var json=$.parseJSON(data);}catch{var json=null;}
if(json){if(json.message){displaySuccess(json.message);}
if(json.redirect){window.location=json.redirect;}}else{displaySuccess(data);}}
if(slide){activateSlide(slide);}}).fail(function(error){displayError(error.responseText);$this.closest(".modalBody").scrollTop(0);}).always(function(){$('button[type="submit"]',$this).buttonReset();});return false;});});$(function(){initFileUploader=function(){$.fn.filepond.registerPlugin(FilePondPluginImagePreview);$.fn.filepond.registerPlugin(FilePondPluginFileValidateType);$.fn.filepond.registerPlugin(FilePondPluginFileValidateSize);$.fn.filepond.registerPlugin(FilePondPluginImageValidateSize);function disableForms(){$("button#submit").attr("disabled",true);}
function enableForms(){$("button#submit").attr("disabled",false);}
$(".fileUploader").filepond({server:{url:"/fileUploader",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},},onaddfile:disableForms,onprocessfile:enableForms,credits:false,});function onAddFile(){$(".meAvatarUploader").removeClass("hide");}
function onRemoveFile(){$(".meAvatarUploader").addClass("hide");}
$(".meAvatarEdit").click(function(){$(".meAvatarUploader").first().removeClass("hide").filepond("browse");});function onError(error){if(error.sub){displayError(error.sub);}
$(".meAvatarUploader").addClass("hide");}
function previewVideo(error,file){var path="/uploads";if(window.location.hostname=="dev.direct.me"){path="https://cdn-dev.direct.me";}else if(window.location.hostname=="direct.me"){path="https://cdn.direct.me";}
var serverPath=file.serverId;var filename=serverPath.split("\\").pop().split("/").pop();var video=$(".videoPreview")[0];video.src=path+"/tmp/"+filename;video.load();video.play();$(".videoPreview").show();enableForms();}
$(".meAvatarUploader").filepond({server:{url:"/profileAvatarUploader.php",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},process:{ondata:function(formData){var accountId=$(".profile-admin-header").data("account-id");if(accountId){formData.append("account_id",accountId);}
return formData;},},},labelIdle:`<span class="filepond--label-action">Change photo</span>`,imagePreviewHeight:170,imageCropAspectRatio:"1:1",imageResizeTargetWidth:200,imageResizeTargetHeight:200,stylePanelLayout:"compact circle",styleLoadIndicatorPosition:"center bottom",styleProgressIndicatorPosition:"right bottom",styleButtonRemoveItemPosition:"left bottom",styleButtonProcessItemPosition:"right bottom",allowRevert:false,acceptedFileTypes:["image/*"],imageValidateSizeMinHeight:200,imageValidateSizeMinWidth:200,onaddfile:onAddFile,onremovefile:onRemoveFile,onerror:onError,credits:false,});$(".challengeAvatarEdit").click(function(){$(".challengeAvatarUploader").first().removeClass("hide").filepond("browse");});$(".challengeAvatarUploader").filepond({server:{url:"/profileAvatarUploader.php",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},},labelIdle:`<span class="filepond--label-action">Change photo</span>`,imagePreviewHeight:170,imageCropAspectRatio:"1:1",imageResizeTargetWidth:200,imageResizeTargetHeight:200,stylePanelLayout:"compact circle",styleLoadIndicatorPosition:"center bottom",styleProgressIndicatorPosition:"right bottom",styleButtonRemoveItemPosition:"left bottom",styleButtonProcessItemPosition:"right bottom",allowRevert:false,acceptedFileTypes:["image/*"],imageValidateSizeMinHeight:200,imageValidateSizeMinWidth:200,onaddfile:function(){$(".challengeAvatarUploader").removeClass("hide");},onremovefile:function(){$(".challengeAvatarUploader").addClass("hide");},onerror:function(error){if(error.sub){displayError(error.sub);}
$(".challengeAvatarUploader").addClass("hide");},onprocessfile:function(){$("#challengeActionBack").click();},credits:false,});$(".imageUploader").filepond({server:{url:"/fileUploader",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},},acceptedFileTypes:["image/*"],onaddfile:disableForms,onprocessfile:enableForms,credits:false,});$(".videoUploader").filepond({server:{url:"/fileUploader",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},},acceptedFileTypes:["video/*"],onaddfile:disableForms,onprocessfile:previewVideo,credits:false,});$(".orderAttachmentUploader").filepond({chunkUploads:true,chunkSize:5000000,server:{url:"/filePondUploader",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},},onprocessfile:function(){$.post(window.location.pathname+"/attach?type=order",{attachment:$(".orderAttachmentUploader input[name=attachment]").val(),}).always(function(){window.location.reload(false);});},credits:false,});$(".attachmentUploader").filepond({server:{url:window.location.pathname+"/attach",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},},onprocessfile:function(){window.location.reload(false);},credits:false,});var $itemImageUploader=$(".itemImageUploader").filepond({server:{url:"/fileUploader",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},},acceptedFileTypes:["image/*"],imagePreviewHeight:170,stylePanelLayout:"compact",onaddfile:addItemImage,credits:false,});var $itemVideoUploader=$(".itemVideoUploader").filepond({chunkUploads:true,chunkSize:5000000,server:{url:"/filePondUploader",headers:{"X-CSRF-Token":$("meta[name=csrf-token]").attr("content"),},},acceptedFileTypes:["video/*"],onaddfile:addItemVideo,credits:false,});$(document).on("click",".iconsGridItem",function(e){e.preventDefault();$itemVideoUploader.filepond("removeFile");$itemImageUploader.filepond("removeFile");});function resetItemIcon(){$(".removeIcon").click();}
function addItemImage(){resetItemIcon();$itemVideoUploader.filepond("removeFile");}
function addItemVideo(){resetItemIcon();$itemImageUploader.filepond("removeFile");}};if($.isFunction($.fn.filepond)){initFileUploader();$(document).ajaxSuccess(function(event,xhr,settings){if(settings.url.indexOf("initFileUploader")!==-1){initFileUploader();}});}
if($.isFunction($.fn.jscroll)){$(".infiniteScroll").jscroll({autoTrigger:true,nextSelector:"a.nextLink:last",});}});$(function(){if($(".inboxScrollToBottom").length){window.scrollTo(0,document.body.scrollHeight);}
$(".inboxSendMessageText").keyup(function(e){if(!isMobileDevice()&&e.which==13&&!e.shiftKey){e.preventDefault();sendMessage();return false;}
if($(this).val().length>0){$(".inboxSendMessageButton").addClass("active",true);$(".inboxSendAttachmentButton").opacity(0.25);}else{$(".inboxSendMessageButton").removeClass("active",false);$(".inboxSendAttachmentButton").opacity(1);}});$(".inboxSendMessageButton").click(function(e){e.preventDefault();sendMessage();return false;});function sendMessage(){var $button=$(".inboxSendMessageButton");var $textarea=$(".inboxSendMessageText");var $form=$("#inboxSendForm");var $inbox=$(".inboxConversation");if($textarea.val().trim().length==0){return false;}
$button.attr("disabled",true);$(".inboxSenderMessageLoading").show();if(!$form.data("send-threads")){window.scrollTo(0,document.body.scrollHeight);}
$textarea.attr("disabled",true);$.post($form.attr("action"),{action:"sendMessage",message:$textarea.val(),},function(data){if($form.data("send-threads")){window.location.reload();}else{$inbox.html(data);window.scrollTo(0,document.body.scrollHeight);$button.attr("disabled",false);$button.removeClass("active");$textarea.val("");$textarea.attr("disabled",false);}});return false;}
$("#showInboxSendAttachment").click(function(e){e.preventDefault();var attach=$(".inboxSendAttachment");var message=$(".inboxSendMessage");if($(attach).hasClass("active")){$(message).slideDown(400);$(attach).slideUp(400,function(){$(this).removeClass("active");});}else{$(attach).slideDown(400,function(){$(this).addClass("active");});$(message).slideUp(400);}
return false;});});$(function(){$(document).on("click",'[data-dismiss="cookienotice"]',function(e){e.preventDefault();var $modal=$(this).closest(".modal");$.post("/cookies",{},function(){closeModal($modal);});return false;});$("#removeAccessImage").click(function(event){event.preventDefault();var $btn=$(this);var $overlay=$("#removeAccessImageOverlay");var $input=$("#removeAccessImageInput");if($input.val()==="1"){$overlay.hide();$input.val("");$btn.text("Remove Image");}else{$overlay.show();$input.val("1");$btn.text("Undo Remove");}});});function _debounce(func,wait,immediate){var timeout;return function(){var context=this,args=arguments;if(immediate&&!timeout)func.apply(context,args);clearTimeout(timeout);timeout=setTimeout(function(){timeout=null;func.apply(context,args);},wait);};}
$(function(){var xhr;var $explorePage=$("#explorePage");var $exploreResults=$("#exploreResults");var $exploreLoading=$("#exploreLoading");var lastQuery;$("#exploreSearch").keyup(_debounce(function(){var query=$(this).val();if(query.length==0){$explorePage.show();$exploreResults.html("");$exploreLoading.hide();return;}
if(query.length>=1&&query.length<3){return;}
if(lastQuery&&lastQuery===query){return;}
lastQuery=query;$explorePage.hide();$exploreResults.html("");$exploreLoading.show();if(xhr&&xhr.readyState!=4){xhr.abort();}
xhr=$.get("/explore",{query:query,},function(data){$exploreLoading.hide();$exploreResults.html(data);});},250,true));});$(function(){var setupImportData=function($result){$(".import-toggle",$result).change(function(){var $this=$(this);var $item=$this.closest(".import-item");var checked=$this.is(":checked");$('input[type="hidden"]',$item).attr("disabled",!checked);$(".import-details",$item).toggleClass("ignore",!checked);});$("#importLinktreeData").submit(function(e){e.preventDefault();var $this=$(this).addClass("loading");var $submit=$("button",$this).attr("disabled",true);$.post("",$this.serialize()).done(function(data){$result.html(data);}).fail(function(error){displayError(error.responseText);}).always(function(){$this.removeClass("loading");$submit.attr("disabled",false);});return false;});};$("#importLinktreeHandle").submit(function(e){e.preventDefault();var $this=$(this).addClass("loading");var $submit=$("button",$this).attr("disabled",true);var $result=$("#importResult");$.post("",$this.serialize()).done(function(data){$this.hide();$result.html(data);setupImportData($result);}).fail(function(error){displayError(error.responseText);}).always(function(){$this.removeClass("loading");$submit.attr("disabled",false);});return false;});});$(function(){var $meStats=$("#meStats");if($meStats.length){$.get("/me/stats",{stat:"views",period:"day",},function(result){$(".meStatsText",$meStats).html("<span class='meStatNumber'>"+
(result.display?result.display:0)+
"</span>View"+
(result.total===1?"":"s")+
" today");}).always(function(){$(".blinkLoading").hide();});}});$(function(){var lazyLoadInstance=new LazyLoad();var initLazyLoad=function(scroll){new LazyLoad({container:scroll,});};new LazyLoad({elements_selector:".scroll",callback_enter:initLazyLoad,unobserve_entered:true,});window.displayAlert=function(message,className){var alert=$('<div class="alert '+
className+
'" style="display: none">'+
message+
"</div>");alert.prependTo("#alerts").fadeIn().delay(4000).fadeOut().queue(function(){$(this).remove();});};window.displayError=function(message){displayAlert(message,"alertError");};window.displaySuccess=function(message){displayAlert(message,"alertSuccess");};$("#resendEmail").on("click",function(){$.get("/verify?resend=1").done(function(data){if(data){displaySuccess(data);}}).fail(function(error){displayError(error.responseText);});return false;});$("#changeEmailForm").submit(function(e){e.preventDefault();$this=$(this);var emailAddress=$("input#emailAddress",$this).val();$.post("/verify",$this.serialize()).done(function(data){displaySuccess(data);$('a[href="#showEmail"]').click();$("#displayEmail").html(emailAddress);}).fail(function(error){displayError(error.responseText);}).always(function(){$this.removeClass("loading");$("button",$this).attr("disabled",false);});});$(document).on("change",".profilePreviewToggle",function(e){var $this=$(this);var $me=$("#meSlide");var $profilePreview=$("#meProfilePreview");var checked=$this.is(":checked");if(checked){$this.addClass("isLoading");$profilePreview.addClass("isLoading").html('<div class="slideLoading"><svg class="bspinner animated infinite spin" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="#8e8e8e" d="M1.379 9.503A15.906 15.906 0 017.715 2.31a2 2 0 112.068 3.424 11.923 11.923 0 00-4.75 5.392c-2.686 6.047.048 13.152 6.094 15.84s13.152-.048 15.84-6.094-.048-13.152-6.094-15.84a11.942 11.942 0 00-4.236-1.02 2 2 0 11.21-3.994c1.95.103 3.85.56 5.65 1.36 8.062 3.582 11.707 13.056 8.124 21.118S17.565 34.204 9.503 30.621-2.204 17.565 1.379 9.503z"/></svg></div>');$profilePreview.addClass("active");$me.removeClass("active").addClass("wasActive");$.get($profilePreview.data("src")+"?preview=1",function(html){$profilePreview.html(html);$this.removeClass("isLoading");$profilePreview.removeClass("isLoading");lazyLoadInstance.update();});}else{$profilePreview.removeClass("active");$me.removeClass("wasActive").addClass("active");$this.removeClass("isLoading");}});});$(function(){var $featuredProfileItemStatic=$("[data-featured-profile-item-static]").first();var $featuredProfileItem=$("[data-featured-profile-item]").first();if($featuredProfileItemStatic.length){$featuredProfileItemStatic.remove().insertAfter("#profile");var $modalInner=$(".modalWithFeaturedOverlay",$featuredProfileItemStatic);$modalInner.css("bottom","-"+$modalInner.height()+"px");$featuredProfileItemStatic.addClass("isVisible");$modalInner.animate({bottom:0},800);}else if($featuredProfileItem.length){var id=$featuredProfileItem.attr("data-target");var $modal=$(id+".modal");var modalClass=$featuredProfileItem.attr("data-modal-class");var url=$featuredProfileItem.attr("data-featured-profile-item");if(!$modal.length){$modal=$('<div id="'+
id.substring(1)+
'" class="modal '+
(modalClass?modalClass:"")+
'"></div>').insertAfter("#profile");}
$.get(url,function(html){$modal.html(html);var $modalInner=$(".modalWithFeaturedOverlay",$modal);$modalInner.css("bottom","-"+$modalInner.height()+"px");setTimeout(function(){$modal.addClass("isVisible");$modalInner.animate({bottom:0,},800);},100);});}});$(function(){$(document).on("click",".animationPreview",function(){var $this=$(this);var value=$this.attr("data-value");if(value){var animation="animate__animated animate__"+value;$this.addClass(animation);setTimeout(function(){$this.removeClass(animation);},1000);}});});$(function(){$(".avatarFeaturedOverlay").each(function(){var $this=$(this);setTimeout(function(){requestAnimationFrame(function(){$this.addClass("avatarFeaturedOverlayDone");});},2400);});});$(function(){$(document).on("click",".addListItem",function(){var $this=$(this);var type=$this.attr("data-type");$this.attr("disabled",true);$('.listItem[data-type="'+type+'"]').show();$("#"+type).focus();});$(document).on("click",".removeListItem",function(){var $this=$(this);var type=$this.attr("data-type");$('.addListItem[data-type="'+type+'"]').attr("disabled",false);$('.listItemType[data-type="'+type+'"]').hide();$("#"+type).val("");});$(document).on("submit",".addListItemForm",function(e){e.preventDefault();var inputs=$(this).serializeArray();var id=$(this).attr("data-id");if(id=="{id}"){var id=$(".listItem").length;var slideTemplate='<div class="slide" id="addMultiLink'+
id+
'">'+
$("#addMultiLink").html().replaceAll("{id}",id)+
"</div>";$("#addMultiLink").before(slideTemplate);var row=$("#listTemplate").html().replaceAll("{id}",id);$(".addList").append(row);$(this).trigger("reset");}
inputs.forEach(function(input){var name=input.name.replace("{id}",id);$('input[name="'+name+'"]').val(input.value);$('[data-preview="'+name+'"]').html(input.value);});activateSlide("#form");return false;});$(document).on("click",".addSlideForm",function(){var slideTemplate=$("#slideTemplate").html().replaceAll("{id}",$(".listItem").length);$("#slideTemplate").after(slideTemplate);activateSlide("#"+$(slideTemplate).attr("id"));});$(document).on("click",".removeListItemForm",function(){var $this=$(this);var id=$this.attr("data-id");var type=$this.attr("data-type");$this.closest('.listItem[data-id="'+id+'"]').remove();$('input[name="item['+id+'][title]"]').val("");});});$(function(){function setViewHeight(){const viewHeight=window.innerHeight;document.documentElement.style.setProperty("--vh",`${viewHeight}px`);}
$(window).on("resize orientationchange",function(){setViewHeight();});setViewHeight();});$(function(){$(document).on("click","[data-toggle=mute]",function(e){e.preventDefault();var $this=$(this).blur();var $video=$($this.attr("data-target"));var muted=$video.prop("muted");$video.prop("muted",!muted);$("svg[data-muted]",$this)[muted?"hide":"show"]();$("svg[data-unmuted]",$this)[muted?"show":"hide"]();});$(document).on("click","[data-toggle=playpause]",function(e){e.preventDefault();var $this=$(this).blur();var $video=$($this.attr("data-target"));var paused=$video.prop("paused");$video.trigger(paused?"play":"pause");$("svg",$this)[paused?"hide":"show"]();});});$(function(){$(document).on("click",".profileReportReason",function(){$("#profileReportReason").val($(this).attr("data-reason"));});});$(function(){var $input=$(".emailVerificationInput");$input.on({paste(ev){ev.preventDefault();const clip=ev.originalEvent.clipboardData.getData("text").trim();if(!/\d{6}/.test(clip))return;const s=[...clip];$input.val((i)=>s[i]).eq(5).focus();},input(ev){const i=$input.index(this);if(this.value)$input.eq(i+1).focus();},keydown(ev){const i=$input.index(this);if(!this.value&&ev.key==="Backspace"&&i)$input.eq(i-1).focus();},});});$(function(){$(document).on("click",'a[data-toggle="show"]',function(e){e.preventDefault();var id=$(this).attr("href");$(id).show();});$(document).on("click","[data-hide-target]",function(e){var id=$(this).attr("data-hide-target");$(id).hide();});});$(document).on("click","[data-copy-input]",function(e){e.preventDefault();var $this=$(this);var text=$this.text();$($this.attr("data-copy-input")).select();document.execCommand("copy");$this.text("Copied!");setTimeout(function(){$this.text(text);},1000);});$(document).on("click",".dropdownToggle",function(e){var parent=$(this).closest(".dropdown");$(".dropdown").not(parent).removeClass("dropdownOpen");parent.toggleClass("dropdownOpen");return false;});$(document).on("click",function(e){if(!$(e.target).closest(".dropdown").length){$(".dropdown").removeClass("dropdownOpen");}});$(function(){if(typeof window.dmAppQ!=="undefined"){window.dmAppQ.forEach(function(func){func();});}});$(function(){$(document).on("submit","#domainSearchForm",function(e){e.preventDefault();var $this=$(this);var domain=encodeURI($("input",$this).val());if(!(domain&&domain.length)){displayError("Please enter keywords or a domain to search for.");}else{var $btn=$("button[type=submit]",$this).buttonLoading();$.post("/domains?action=search",{domain}).done(function(data){$("#linkDomain").html(data);$('a[data-toggle="slide"]',$this).click();}).always(function(){$btn.buttonReset();});}});});